# Generated by Django 4.2.7 on 2024-01-27 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128)),
                ('url', models.CharField(blank=True, max_length=128)),
                ('youtubeID', models.CharField(blank=True, max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='VideoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='api.tag')),
                ('video', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='api.video')),
            ],
        ),
    ]
