# Generated by Django 4.2.7 on 2024-01-27 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videotag',
            old_name='Tag',
            new_name='tag',
        ),
    ]
