# Generated by Django 4.2.7 on 2024-01-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_tag_videotag_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
