# Generated by Django 4.2.7 on 2024-01-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_video_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='tags',
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
