# Generated by Django 4.2.7 on 2024-01-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_video_tags_alter_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
