# Generated by Django 4.2.7 on 2024-01-27 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_video_tags_alter_video_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='tags',
        ),
    ]
