# Generated by Django 4.2.7 on 2024-01-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_video_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
