# Generated by Django 4.2.7 on 2024-02-24 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_video_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='tags',
        ),
    ]
