# Generated by Django 4.2.7 on 2024-02-24 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_video_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotag',
            name='tag',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.tag'),
        ),
        migrations.AlterField(
            model_name='videotag',
            name='video',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.video'),
        ),
    ]
