# Generated by Django 4.2.7 on 2024-04-25 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_videotag_tag_alter_videotag_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtubeID',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='videotag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tag'),
        ),
        migrations.AlterField(
            model_name='videotag',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.video'),
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('videos', models.ManyToManyField(to='api.video')),
            ],
        ),
    ]
