# Generated by Django 4.2.7 on 2024-04-25 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_video_title_alter_video_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VideoListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('VideoList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.videolist')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.video')),
            ],
        ),
        migrations.DeleteModel(
            name='List',
        ),
        migrations.AddField(
            model_name='videolist',
            name='videos',
            field=models.ManyToManyField(blank=True, null=True, through='api.VideoListItem', to='api.video'),
        ),
    ]
