# Generated by Django 4.2.7 on 2024-04-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_videolist_videolistitem_delete_list_videolist_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolist',
            name='videos',
            field=models.ManyToManyField(through='api.VideoListItem', to='api.video'),
        ),
    ]
