# Generated by Django 4.2.7 on 2024-04-27 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_alter_videolist_videos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videolistitem',
            old_name='VideoList',
            new_name='videoList',
        ),
        migrations.AddField(
            model_name='videolist',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
